---
title: "Pdam_BW_Panama"
author: "Ana Palacio"
date: "July 26, 2019"
output:
  html_document:
    fig_height: 3.5
    fig_width: 3.5
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) 
                      #fig.width=4, fig.height=3 )
```

# General project set-up 

```{r libraries, results="hide"}

# Libraries
  library(reshape2)
  library(tidyverse)

# Graphs
    ggthe_bw<-theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )+
    theme_bw()
    
# Data    
  # Fragment list
  CurrentFragments<-read.csv("Metadata/Fragment_Replicate.csv", header = T)

  # Collection information
  Location<-read.csv("Metadata/Genotype_Origin.csv", header = T)
```

# Raw data

Data files
```{r}

# BW data
  Raw_Data<-read.csv("RawData.csv")
  n_RunA <- data.frame(table(Raw_Data$Fragment))
  colnames(n_RunA)<-c("Fragment","Samples")
  
  N_Sample_Date<-Raw_Data %>%
         group_by(Fragment, Date) %>%
         dplyr::summarise(N = n())
  N_Sample_Date


```

Re organize the data

```{r}
Raw_Data_Wide<-reshape(Raw_Data, idvar="Fragment", timevar = "Time", direction = "wide")

Raw_Data_Wide<-dplyr::left_join(Raw_Data_Wide,CurrentFragments, by ="Fragment")
#Raw_Data_2<-dplyr::left_join(Raw_Data,CurrentFragments, by ="Fragment")
#Typos<-dplyr::anti_join(Raw_Data, CurrentFragments, by ="Fragment")

Raw_Data_Wide<-dplyr::left_join(Raw_Data_Wide, n_RunA, by="Fragment")
Raw_Data_Wide<-left_join(Raw_Data_Wide, Location, by=c("Colony"))

write.csv(Raw_Data_Wide, "Raw_Data_Wide3.csv", row.names = FALSE)

# Clean working space
rm(list = ls())
```

# Organized data

After data manupulation

```{r}

# Long (processed) data
Corrected_long<-read.csv("Long_data_GrowthRates_3.csv")
  n_RunB <- data.frame(table(Corrected_long$Fragment))
  colnames(n_RunB)<-c("Fragment","Samples")

Corrected_long<-dplyr::left_join(Corrected_long, CurrentFragments, by ="Fragment")
#Typos<-dplyr::anti_join(Corrected_long, CurrentFragments, by ="Fragment")
Corrected_long<-dplyr::left_join(Corrected_long, n_RunB, by ="Fragment")
Corrected_long<-left_join(Corrected_long, Location, by=c("Colony"))



    Corrected_long$Date_I<-as.Date(Corrected_long$Date_I, "%m/%d/%y")
    Corrected_long$Date_F<-as.Date(Corrected_long$Date_F, "%m/%d/%y")
    # Corrected_long$Date_I<-as.Date(Corrected_long$Date_I, "%Y-%m-%d")
    # Corrected_long$Date_F<-as.Date(Corrected_long$Date_F, "%Y-%m-%d")
    Corrected_long$Days<-(as.numeric(as.Date(Corrected_long$Date_F))-18173)
    Corrected_long$Day<-(as.factor(Corrected_long$Days))
    Corrected_long$Colony <- paste("P",Corrected_long$Colony, sep = "_" )
    Corrected_long$Colony <- as.factor(Corrected_long$Colony)
    
    Corrected_long$SampleID <- paste(Corrected_long$Colony, Corrected_long$Date_F, sep = "_")

# Remove dead frags
  Dying_frags<-filter(Corrected_long, Notes_I=="Almost Dead")
  Dying_frags<-select(Dying_frags, Fragment)
  Corrected_long<-anti_join(Corrected_long, Dying_frags, by = "Fragment")
  str(Corrected_long)

#write.csv(Corrected_long, "Corrected_long3.csv", row.names = FALSE)

 Corrected_long<-filter(Corrected_long, Time>5)
 Corrected_long<-filter(Corrected_long, Reef!="NA")
 
  
```

## Reef

```{r}

BW_Reef<- ggplot(Corrected_long, aes (Reef, mg.g.d_corrected_NA, shape=factor(ORF), colour=factor(ITS2))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_Reef

BW_Reef<- ggplot(Corrected_long, aes (Date_F, mg.g.d_corrected_NA, shape=factor(Reef),
                                    colour=factor(Reef))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_Reef

BW_Reef<- ggplot(Corrected_long, aes (Time, mg.g.d_corrected_NA, shape=factor(ORF),
                                    colour=factor(Reef))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_Reef + facet_wrap(~ITS2)



```

## ITS2

```{r}
BW_ITS2<- ggplot(Corrected_long, aes (Date_F, mg.g.d_corrected_NA, shape=factor(ITS2),
                                    colour=factor(ITS2))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_ITS2

BW_ITS2<- ggplot(Corrected_long, aes (Time, mg.g.d_corrected_NA, shape=factor(ITS2),
                                    colour=factor(ITS2))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_ITS2 + facet_wrap(~ORF)


BW_ITS2<- ggplot(Corrected_long, aes (Time, mg.g.d_corrected_NA, colour=factor(ORF))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_ITS2 + facet_wrap(~ITS2)

```


```{r}
BW_Colony<- ggplot(Corrected_long, aes (Colony, mg.g.d_corrected_NA, shape=factor(Init_Symbiont),
                                    colour=factor(Reef))) + 
      ggthe_bw + #Fill.colour+
      stat_summary(fun.data = "mean_cl_boot", geom = "errorbar",
                   position=position_dodge(width=0.1))+
      stat_summary(fun.y=mean, geom="line", 
                   position=position_dodge(width=.11), linetype=2) +
      stat_summary(fun.y=mean, geom="point", size =2,
                   position=position_dodge(width=0.1))  + 
  
      geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_Colony 
BW_Colony + facet_grid(ORF~ITS2)
```


```{r}
BW_Frag<- ggplot(Corrected_long, aes (Time, mg.g.d_corrected_NA, group=(Fragment),
                                    colour=factor(Reef))) + 
      ggthe_bw + #Fill.colour+
      geom_line()+
        geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_Frag+facet_wrap(~Colony)

BW_Frag<- ggplot(Corrected_long, aes (Time, mg.g.d_no_corrected_NA, group=(Fragment),
                                    colour=factor(Reef))) + 
      ggthe_bw + #Fill.colour+
      geom_line()+
        geom_hline(yintercept = 0, linetype=3)+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      #scale_y_continuous(name="Growth (mg / g d)", 
        #                 breaks = seq(-1, 4, by=1)) +
    
    theme(legend.position="bottom",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW_Frag+facet_wrap(~Colony)
```
