---
title: "Tank conditions"
author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
      code_folding: "hide"
      toc: true
      df_print: paged
      theme: united
bibliography: packages.bib
nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) 
                      #fig.width=4, fig.height=3 )
```

# General project set-up 

```{r libraries, results="hide"}

# Libraries
  library(reshape2)
  library(tidyverse)
  library(tidyr)
  library(lubridate)
  library(gridExtra)

# Graphs

theme_set (theme_classic() + theme(panel.grid.major = element_blank(),
                              panel.grid.minor = element_blank(), 
                              axis.line = element_line(colour = "black"),
                              legend.position="bottom",
                              legend.title=element_blank(),
                              #axis.text.x = element_text(angle = 90, vjust = 0.5),
                              plot.title = element_text(size=12, face="bold"),
                              panel.border = element_rect(colour = "black", fill=NA, size=1)
                              #panel.border = element_blank()
                              ))

# col_4_col<-scale_colour_manual(values = c("#88CCEE",  "#332288",
#                                           "#DDCC77","#117733"))
# col_4_fill<-scale_fill_manual(values = c("#88CCEE",  "#332288",
#                                           "#DDCC77","#117733"))

col_4_col<-scale_colour_manual(values = c("deepskyblue", "indianred1", "blue4", "red4"))

col_4_fill<-scale_fill_manual(values = c("deepskyblue", "indianred1", "blue4", "red4"))
```




# Temperature data

```{r}
Temperature.data<-read.csv("Data/Temp_experiment.csv", header = T)
summary(Temperature.data)

# Data types
    Temperature.data$Temperature<-as.numeric(Temperature.data$Temperature)
    Temperature.data$Tank<-as.factor(Temperature.data$Tank)
    Temperature.data$Content<-factor(Temperature.data$Content)
    Temperature.data$Time<-strptime(Temperature.data$Time, "%Y-%m-%d %H:%M:%S")
    Temperature.data$Time <- as.POSIXct(Temperature.data$Time)
    Temperature.data$Date<-as.Date(ymd_hms(Temperature.data$Time))
    
    Temperature.data<- Temperature.data %>%
       group_by(Tank, Content, Date)%>%
            dplyr::summarise(Temperature=mean(Temperature))
    Temperature.data
    
    Temperature.data$Day<-weekdays(Temperature.data$Date)
    Temperature.data$Data<-ifelse (Temperature.data$Day=="Friday",
                         15, NA)
    Temperature.data$Day<-as.numeric(Temperature.data$Date)-18518
    Temperature.data<-Temperature.data[Temperature.data$Day>0, ]
    
    Temperature.data$Week<-(Temperature.data$Day)/7
    Temperature.data$Week<-as.integer(Temperature.data$Week)+1
    summary(Temperature.data)

```


```{r}
ExperimentTemperature<- ggplot(Temperature.data) +
  #geom_vline(xintercept=1500)+
  
  geom_jitter(aes(Date, Temperature, colour=factor(Content)),
              alpha=0.5, size=0.01)+
  geom_line(aes(Date, Data), alpha=1, size=0.05)+
  scale_y_continuous(limits = c(15, 35),
                         breaks = seq(15, 35, 2),  
                         expand = c(0, 0),
                         name=("Temperature (C)"))

ExperimentTemperature+facet_wrap(~Tank)

```

# Salinity data

```{r}
## Salinity
    Salinity.data<-read.csv("Data/System.csv")
    Salinity.data<-Salinity.data %>% select(Time, Salinity)
    Salinity.data$Time<-strptime(Salinity.data$Time, "%m/%d/%y %H:%M")
    Salinity.data$Time <- as.POSIXct(Salinity.data$Time)
    Salinity.data$Date <- as.Date(Salinity.data$Time)
    
    Salinity.data<- Salinity.data %>%
       group_by(Date)%>%
            dplyr::summarise(Salinity=mean(Salinity))
    Salinity.data
    
    Temperature.data<-left_join(Temperature.data, Salinity.data, by=("Date"))
```


# Tank treatment info
```{r}
# Get tank treatment info  

  Tank.info<-read.csv("Data/Tank_treatment.csv", header = T)

# Merge with temperature
  Temperature.data<-left_join(Temperature.data, Tank.info, by=("Tank"))
  
  Temperature.data$Treatment<-factor(Temperature.data$Combo, levels = c("Ambient+Placebo", "Ambient+Disease", 
                                                              "NH4+Placebo", "NH4+Disease"))
```
 
## Temp + Sal plot

```{r}

meanTemp<-ggplot(Temperature.data, aes(Week, Temperature, fill=Treatment)) +
  geom_line(data=Temperature.data, aes(x=Temperature.data$Day/7, y=Temperature.data$Salinity),
            linetype=2, colour="gray60") + 
  
  stat_summary(fun=mean, geom="line", position=position_dodge(width=0.3)) +
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", width = 0.2, position=position_dodge(width=0.3)) + 
  stat_summary(fun=mean, geom="point", shape=21, size=3, position=position_dodge(width=0.3)) +
  
  scale_x_continuous(limits = c(0.8, 9.2),
                      breaks = seq(1, 9, 1),  
                      expand = c(0, 0))+
  scale_y_continuous(limits = c(25, 33),
                     # breaks = seq(0, 35, 2),  
                     # expand = c(0, 0),
                    name=expression("Temperature ("~degree~"C)"))+
  geom_vline(xintercept=7.8, linetype="dashed", colour="indianred1") +
  geom_vline(xintercept=7.81, linetype="dashed", colour="red4") +
  col_4_fill+
  col_4_col
meanTemp

#ggsave(file="Outputs/Temperature_plot.svg", meanTemp, width=5.5, height=4)

```

## Temp and sal summary 

```{r}
Temp.Summary<- as.data.frame(Temperature.data %>%
  group_by(Week, Treatment) %>%
  summarize(Temp_mean = mean (Temperature,  na.rm = T),
            Temp_sd = sd (Temperature,  na.rm = T)))
Temp.Summary<-reshape(Temp.Summary, idvar = "Treatment", timevar = "Week", direction = "wide")
Temp.Summary
#write.csv(Temp.Summary, "Outputs/Temp_Summary.csv", row.names = F)

Temp.Summary<- as.data.frame(Temperature.data %>%
  group_by(Treatment) %>%
  summarize(Temp_mean = mean (Temperature,  na.rm = T),
            Temp_sd = sd (Temperature,  na.rm = T)))
Temp.Summary<-reshape(Temp.Summary, idvar = "Treatment", timevar = "Week", direction = "wide")
Temp.Summary
#write.csv(Temp.Summary, "Outputs/Temp_Summary.csv", row.names = F)


Sal.Summary<- as.data.frame(Temperature.data %>%
  group_by(Week, Treatment) %>%
  summarize(Sal_mean = min (Salinity,  na.rm = T),
            Sal_sd = sd (Salinity,  na.rm = T)))
Sal.Summary<-reshape(Sal.Summary, idvar = "Treatment", timevar = "Week", direction = "wide")
Sal.Summary
write.csv(Sal.Summary, "Outputs/Sal_Summary.csv", row.names = F)
```


# Nutrients

```{r}
# Nutrients
Nutrients<-read.csv("Data/Nutrients.csv")
summary(Nutrients)
  
  # Nutrients$Date<-as.Date(Nutrients$Date, "%m-%d-%Y")
  # Nutrients$Time<-paste(Nutrients$Date, Nutrients$Hour, sep = " ")
  # Nutrients$Time<-strptime(Nutrients$Time, "%Y-%m-%d %H:%M:%S")
  # Nutrients$Time <- as.POSIXct(Nutrients$Time)
  # Nutrients$Date <- as.Date(Nutrients$Time)
  # Nutrients$Day<-as.numeric(Nutrients$Date)-18518
  # Nutrients$Week<-(Nutrients$Day)/7
  # Nutrients$Week<-as.integer(Nutrients$Week)+1
  Nutrients$Treatment<-factor(Nutrients$Treatment, levels = c("Ambient+Placebo", "Ambient+Disease",
                                                               "NH4+Placebo", "NH4+Disease"))
  summary(Nutrients)
  #write.csv(Nutrients, "Nutrients.csv")
  

# Tall format
  # Nutrients.tall <- gather(Nutrients, Nutrient, Concentration, 
  #                     NH4:PO4.uM., factor_key=TRUE)
  # Nutrients.tall$Date<-as.Date(Nutrients.tall$Date, "%m-%d-%Y")
  # #Nutrients.tall$Time<-paste(Nutrients.tall$Date, Nutrients$Hour, sep = " ")
  # summary(Nutrients.tall)
  
```

## NH4

```{r}
NH4Plot<- ggplot(filter(Nutrients, Treatment!="Source"),
                       aes (Week, NH4, fill=Treatment)) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun=mean, geom="line") + 
  stat_summary(fun=mean, geom="point", shape=21, size=3) +
  
  scale_x_continuous(limits = c(0.8, 9.2),
                      breaks = seq(1, 9, 1),  
                      expand = c(0, 0))+
  scale_y_continuous(#limits = c(0, 20),
                     # breaks = seq(0, 35, 2),  
                     # expand = c(0, 0),
                          name=expression(NH[4]~"["~mu~"M]"))+
 geom_vline(xintercept=7.8, linetype="dashed", colour="indianred1") +
  geom_vline(xintercept=7.81, linetype="dashed", colour="red4") +
  #geom_vline(xintercept=7.8, linetype="dashed", colour="#990033") +
  col_4_fill
  
NH4Plot

#ggsave(file="Outputs/NH4_plot.svg", NH4Plot, width=5.5, height=4.0)
```

## PO4

```{r}
PH4_plot<- ggplot(filter(Nutrients, Treatment!="Source"),
                       aes (Week, PO4.uM., fill=Treatment)) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun=mean, geom="line") + 
  stat_summary(fun=mean, geom="point", shape=21, size=3) +
  scale_x_continuous(limits = c(0.8, 9.2),
                      breaks = seq(1, 9, 1),  
                      expand = c(0, 0))+
  scale_y_continuous(name=expression(PO[4]~"["~mu~"M]"))+
  #geom_vline(xintercept=7.8, linetype="dashed", colour="#990033") +
   geom_vline(xintercept=7.8, linetype="dashed", colour="indianred1") +
  geom_vline(xintercept=7.81, linetype="dashed", colour="red4") +
  col_4_fill
PH4_plot

#ggsave(file="Outputs/PO4_plot.svg", PH4_plot, width=5.5, height=4.0)
```

## Nutrients summary 

```{r}
NH4.Summary<- as.data.frame(Nutrients %>%
  group_by(Week, Treatment) %>%
  summarize(NH4_mean = mean (NH4,  na.rm = T),
            NH4_sd = sd (NH4,  na.rm = T)))
NH4.Summary<-reshape(NH4.Summary, idvar = "Treatment", timevar = "Week", direction = "wide")
NH4.Summary
#write.csv(NH4.Summary, "Outputs/NH4_Summary.csv", row.names = F)

PO4.Summary<- as.data.frame(Nutrients %>%
  group_by(Week, Treatment) %>%
  summarize(PO4_mean = min (PO4.uM.,  na.rm = T),
            PO4_sd = sd (PO4.uM.,  na.rm = T)))
PO4.Summary<-reshape(PO4.Summary, idvar = "Treatment", timevar = "Week", direction = "wide")
PO4.Summary
#write.csv(PO4.Summary, "Outputs/PO4_Summary.csv", row.names = F)
```

# Tank conditions plot

```{r}
TanksPlot<-grid.arrange(meanTemp + theme(legend.position = "none",
                              axis.text.x=element_blank(),
                              axis.title.x = element_blank()),
             NH4Plot + theme(legend.position = "none",
                             axis.text.x=element_blank(), 
                             axis.title.x = element_blank()),
             PH4_plot, nrow=3)
#ggsave(file="Outputs/Tanks.svg", TanksPlot, width=7, height=7)
```


# Packages used

```{r}
# Creates bibliography 
#knitr::write_bib(c(.packages()), "packages.bib")
```
