---
title: "Acer LE under nutrients and disease"
author: "Ana M. Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
      toc: true
      df_print: paged
      theme: united
bibliography: packages.bib
nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) 
                      #fig.width=4, fig.height=3 )
```

# General project set-up 

```{r libraries, results="hide"}

# Libraries
  library(reshape2)
  library(tidyverse)

# Graphs

theme_set (theme_classic() + theme(panel.grid.major = element_blank(),
                              panel.grid.minor = element_blank(), 
                              axis.line = element_line(colour = "black"),
                              legend.position="bottom",
                              axis.text.x = element_text(angle = 90, vjust = 0.5),
                              plot.title = element_text(size=12, face="bold"),
                              #panel.border = element_rect(colour = "black", fill=NA, size=1)
                              panel.border = element_blank()
                              ))

    
```


# Meta data

* Treatments, Genotypes, Tags

```{r}

# # Treatment Info
#   Treatment<-read.csv("Data/Treatments.csv")
#   #duplicated(Treatment$Tag)
#   Treatment<-Treatment[!duplicated(Treatment$Tag), ]
#   #duplicated(Treatment$Tag)
#   summary(Treatment)

```

# LE data 

```{r}

# 1. BW data
  LE_Tall<-read.csv("Data/Linear_Extension.csv")
  
# 2. Data clean-up an types: 
  
  # Variable types 
    #BW_Tall$Time <- as.factor(BW_Tall$Time)
    #BW_Tall$Time<-as.numeric(BW_Tall$Time)
    LE_Tall$Date<-as.Date(LE_Tall$Date, "%Y-%m-%d")
    LE_Tall$Day<-(as.numeric(LE_Tall$Date)-18486)
  
  
# 3. Merge with treatments
    # LE_Tall<-plyr::join(LE_Tall, Treatment, by = "Tag", 
    #             type = "left", match = "all")
    # 
    # LE_Tall<-plyr::join(LE_Tall, Tags, by = "Tag", 
    #             type = "left", match = "all")
    
    LE_Tall$Nutrients<-factor(LE_Tall$Nutrients, 
                             levels= c("Ambient", "NH4"), ordered=TRUE)
    LE_Tall$Disease<-factor(LE_Tall$Disease, 
                             levels= c("Placebo", "Pathogen"), ordered=TRUE)

# 4. Replicates
    LE_Tall$Tank<-factor(LE_Tall$Tank, ordered=FALSE)
    LE_Tall$Genotype<-factor(LE_Tall$Genet, ordered=FALSE)

    summary(LE_Tall)

```

# 1. Calculate days bw LE data points
```{r}

LE_Tall<-LE_Tall[order(LE_Tall$Tag), ]

# Calculate days bw BW data points
LE_Tall<-LE_Tall %>%
  group_by(Tag) %>%
  dplyr::mutate(Days = Day - lag(Day, default = Day[1]))

# Calculate change in BW bw data points

LE_Tall<-LE_Tall %>%
  group_by(Tag) %>%
  dplyr::mutate(d_Lenght = Mean_Length - lag(Mean_Length, default = Mean_Length[1]))

LE_Tall<-LE_Tall %>%
    group_by(Tag) %>%
    dplyr::mutate(d_Lenght_r = d_Lenght/(Days*lag(Mean_Length, default = Mean_Length[1])))
  
```


```{r}

BW.CRF<-LE_Tall[which(LE_Tall$Genotype=='K2'|
                      LE_Tall$Genotype=='U41'|
                      LE_Tall$Genotype=='U44'), ]

BW.UM<-LE_Tall[which(LE_Tall$Genotype=='Acerv2'|
                      LE_Tall$Genotype=='Cooper-9'|
                      LE_Tall$Genotype=='Elkhorn'|
                      LE_Tall$Genotype=='Kelsey-1'), ]

BW.UM<-LE_Tall[which(LE_Tall$Genotype=='Acerv2'|
                      LE_Tall$Genotype=='Cooper-9'|
                      LE_Tall$Genotype=='Elkhorn'|
                      LE_Tall$Genotype=='Kelsey-1'), ]

```

## LE Exploration 

```{r}

SizeBiasCheck<- ggplot(data=filter(LE_Tall, Days==14), aes (Mean_Length, d_Lenght*10,
                                     colour=factor(Genotype), 
                                     shape=factor(Nutrients))) +
  geom_jitter(alpha=0.5) + 
  geom_abline(slope = 0, intercept = 0)+
  scale_y_continuous(limits = c(-10, 8),
                         breaks = seq(-10, 8, by=2),  
                         expand = c(0, 0),
                         name=("growth (mm / 14 days)"))+
  scale_x_continuous(limits = c(2.5, 13),
                         breaks = seq(2.5, 13, by=2.5),  
                         expand = c(0, 0),
                         name=("Intitial size (cm)"))
ggExtra::ggMarginal(
  p = SizeBiasCheck,
  type = 'boxplot',
  margins = 'both',
  size = 5,
  colour = 'black',
  fill = 'gray'
)

Plot1<- ggplot(data=filter(LE_Tall, Days==14), aes (Nutrients, d_Lenght*10,
                                     colour=factor(Genotype))) +
  geom_jitter(alpha=0.5) + 
  geom_abline(slope = 0, intercept = 0, linetype=3)+
  scale_y_continuous(limits = c(-10, 8),
                         breaks = seq(-10, 8, by=2),  
                         expand = c(0, 0),
                         name=("growth (mm / 14 days)"))
Plot1


SizeBiasCheck<- ggplot(data=filter(LE_Tall, Days==14), 
                       aes (Mean_Length, d_Lenght*10, 
                            colour=factor(Nutrients))) +
  geom_jitter(alpha=0.5) + 
  geom_abline(slope = 0, intercept = 0, linetype=3)+
  scale_y_continuous(limits = c(-10, 8),
                         breaks = seq(-10, 8, by=2),  
                         expand = c(0, 0),
                         name=("growth (mm / 14 days)"))+
   scale_x_continuous(limits = c(2.5, 13),
                         breaks = seq(2.5, 13, by=2.5),  
                         expand = c(0, 0),
                         name=("Intitial size (cm)"))
SizeBiasCheck
```

## Genotype

```{r}
 
Lenght_Genet<- ggplot(LE_Tall, aes (Date, Mean_Length, colour=factor(Genotype))) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") + 
  geom_jitter(alpha=0.3, width=0.4) +
  scale_y_continuous(limits = c(0, 14),
                         breaks = seq(0, 15,2),  
                         expand = c(0, 0),
                         name=("lenght (cm)"))+
  theme(legend.position = "bottom")

#Lenght_Genet
Lenght_Genet+facet_grid(~Nutrients)
Lenght_Genet+facet_grid(Disease~Nutrients)

d_L_Trea<- ggplot(data=filter(LE_Tall, Days==14),
                   aes (Nutrients, d_Lenght*10, fill=factor(Nutrients))) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") + 
  geom_jitter(alpha=0.3, shape=21) +
  scale_y_continuous(limits = c(-10, 7),
                      breaks = seq(-10, 7, 2),  
                      expand = c(0, 0),
                      name=("growth (mm in 14 days)"))+
  theme(legend.position = "bottom")+
  geom_abline(slope = 0, intercept = 0, linetype=3)
  
d_L_Trea
d_L_Trea+ facet_wrap(~Genotype)
d_L_Trea + facet_wrap(Nutrients~Disease)


d_L_Genet<- ggplot(data=filter(LE_Tall, Days==14),
                   aes (Nutrients, d_Lenght, 
                        colour=factor(Genotype))) +
  geom_jitter(alpha=0.3) +
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") + 
    #scale_y_continuous(limits = c(-2, 6),
     #                    breaks = seq(-2, 10, 1),  
      #                   expand = c(0, 0),
       #                  name=("dBW [mg / g*day]"))+
  theme(legend.position = "bottom")
  
d_L_Genet
d_L_Genet+ facet_wrap(~Nutrients)
d_L_Genet + facet_wrap(Nutrients~Disease)
```


# Packages used

```{r}
# Creates bibliography 
#knitr::write_bib(c(.packages()), "packages.bib")
```
