---
title: "Analyze Acer Temps nutrients and disease"
author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
      toc: true
      df_print: paged
      theme: united
bibliography: packages.bib
nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) 
                      #fig.width=4, fig.height=3 )
```

# General project set-up 

```{r libraries, results="hide"}

# Libraries
  library(reshape2)
  library(tidyverse)
  library(tidyr)
  library(lubridate)

# Graphs

theme_set (theme_classic() + theme(panel.grid.major = element_blank(),
                              panel.grid.minor = element_blank(), 
                              axis.line = element_line(colour = "black"),
                              legend.position="bottom",
                              #axis.text.x = element_text(angle = 90, vjust = 0.5),
                              plot.title = element_text(size=12, face="bold"),
                              panel.border = element_rect(colour = "black", fill=NA, size=1)
                              #panel.border = element_blank()
                              ))
```


# Data

```{r}
Temperature<-read.csv("Temp_experiment.csv", header = T)
summary(Temperature)

# Data types
    Temperature$Temperature<-as.numeric(Temperature$Temperature)
    Temperature$Tank<-as.factor(Temperature$Tank)
    Temperature$Content<-factor(Temperature$Content)
    Temperature$Time<-strptime(Temperature$Time, "%Y-%m-%d %H:%M:%S")
    Temperature$Time <- as.POSIXct(Temperature$Time)
    Temperature$Day<-as.Date(ymd_hms(Temperature$Time))
    Temperature$Day<-weekdays(Temperature$Day)
    Temperature$Data<-ifelse (Temperature$Day=="Friday",
                         15, NA)
    Temperature$Date<-as.Date(Temperature$Time)
    Temperature$Day<-as.numeric(Temperature$Date)-18518
    summary(Temperature)

```

# Data viz

```{r}
ExperimentTemperature<- ggplot(Temperature) +
  #geom_vline(xintercept=1500)+
  
  geom_jitter(aes(Time, Temperature, colour=factor(Content)),
              alpha=0.5, size=0.01)+
  geom_point(aes(Time, Data), alpha=1, size=0.05)+
  scale_y_continuous(limits = c(15, 35),
                         breaks = seq(15, 35, 2),  
                         expand = c(0, 0),
                         name=("Temperature (C)"))

ExperimentTemperature+facet_wrap(~Tank)

```

# Tank treatment info
```{r}
# Get tank treatment info  
  Tank.info<-read.csv("Tank_treatment.csv", header = T)

# Merge with temperature
  Temperature<-plyr::join(Temperature, Tank.info, 
                    by = c("Tank"),
                    type = "left")
```
 
# Plot

```{r}

meanTemp<-ggplot(Temperature, aes(Day, Temperature, 
                                  group=Tank, colour=Replicate)) +
  geom_vline(xintercept=48, linetype="dashed")+
  stat_summary(fun.data = "mean_cl_boot", geom = "errorbar")+
  stat_summary(fun=mean, geom="line") + 
  #geom_jitter(alpha=0.1, size=0.1)+
  scale_y_continuous(limits = c(22, 30),
                         breaks = seq(15, 30, 2),  
                         expand = c(0, 0),
                         name=expression("Temperature ("*~degree*C*")"))+
  scale_x_continuous(limits = c(0, 59),
                         breaks = seq(0, 60,7),  
                         expand = c(0, 0),
                         name=("Days in the experiment"))+
  facet_grid(Disease~Nutrients)+
  theme( legend.position=c(0.1, 0.15))

meanTemp

#ggsave(file="Outputs/Temperature_plot.svg", meanTemp, width=5.5, height=4.5)

```

# Summary 

```{r}
Temperature$Week<-lubridate::week(ymd(Temperature$Date))-36

Temp.Summary<- Temperature %>%
  group_by(Week, Nutrients, Disease, Replicate) %>%
  summarize(Temp_mean = mean (Temperature,  na.rm = T),
            Temp_sd = sd (Temperature,  na.rm = T),
            Temp_min = min (Temperature,  na.rm = T),
            Temp_max = max (Temperature,  na.rm = T)
            )
Temp.Summary

Temp.Summary_all<- Temperature %>%
  group_by(Nutrients, Disease, Replicate) %>%
  summarize(Temp_mean = mean (Temperature,  na.rm = T),
            Temp_sd = sd (Temperature,  na.rm = T),
            Temp_min = min (Temperature,  na.rm = T),
            Temp_max = max (Temperature,  na.rm = T)
            )
Temp.Summary_all
write.csv(Outputs/Temp.Summary_all, "Temp.Summary_all.csv", row.names = F)
```

# Packages used

```{r}
# Creates bibliography 
#knitr::write_bib(c(.packages()), "packages.bib")
```
