---
title: "Acer Temps nutrients and disease"
author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
      toc: true
      df_print: paged
      theme: united
bibliography: packages.bib
nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) 
                      #fig.width=4, fig.height=3 )
```

# General project set-up 

```{r libraries, results="hide"}

# Libraries
  library(reshape2)
  library(tidyverse)
  library(tidyr)
  library(lubridate)

# Graphs

theme_set (theme_classic() + theme(panel.grid.major = element_blank(),
                              panel.grid.minor = element_blank(), 
                              axis.line = element_line(colour = "black"),
                              legend.position="bottom",
                              axis.text.x = element_text(angle = 90, vjust = 0.5),
                              plot.title = element_text(size=12, face="bold"),
                              #panel.border = element_rect(colour = "black", fill=NA, size=1)
                              panel.border = element_blank()
                              ))
```


# Data

## Nutrients

```{r}
# Nutrients

Nutrients<-read.csv("Data/Nutrient samples_round4.csv")
  summary(Nutrients)
  
  #Nutrients$Date<-as.Date(Nutrients$Date, "%m-%d-%Y")
  #Nutrients$Time<-paste(Nutrients$Date, Nutrients$Hour, sep = " ")

  #Nutrients$Time<-strptime(Nutrients$Time, "%Y-%m-%d %H:%M:%S")
  #Nutrients$Time <- as.POSIXct(Nutrients$Time)
  #Nutrients$Date <- as.Date(Nutrients$Time)
  
summary(Nutrients)

# Tall format
  Nutrients.tall <- gather(Nutrients, Nutrient, Concentration, 
                      NH4:PO4.uM., factor_key=TRUE)
  Nutrients.tall$Date<-as.Date(Nutrients.tall$Date, "%m-%d-%Y")
  Nutrients.tall$Time<-paste(Nutrients.tall$Date, Nutrients$Hour, sep = " ")

  Nutrients.tall$Time<-strptime(Nutrients.tall$Time, "%Y-%m-%d %H:%M:%S")
  Nutrients.tall$Time <- as.POSIXct(Nutrients.tall$Time)
  Nutrients.tall$Date <- as.Date(Nutrients.tall$Time)
  
  summary(Nutrients.tall)
  
```

## Salinity

```{r}
# Precipitation
  Precipitation<-read.csv("Data/Precipitation.csv")

  Precipitation$Time<-paste(Precipitation$Date, Precipitation$Hour, sep = " ")
  Precipitation$Time<-strptime(Precipitation$Time, "%Y-%m-%d %H:%M:%S")
  Precipitation$Time <- as.POSIXct(Precipitation$Time)

  Precipitation$Date<-as.Date(Precipitation$Date, "%Y-%m-%d")
  

# Salinity
  Salinity<-read.csv("Data/System.csv")
  Salinity$Time<-strptime(Salinity$Time, "%m/%d/%Y %H:%M:%S")
  Salinity$Time <- as.POSIXct(Salinity$Time)
  Salinity$Date <- as.Date(Salinity$Time)
  summary(Salinity)
  
  
Summary.Salinity<- Salinity %>%
  group_by(Date)%>%
  dplyr::summarise(mean=mean(Salinity), 
            min=min(Salinity),
            max=max(Salinity))

Summary.Salinity<-left_join(Summary.Salinity, Precipitation, by=("Date"))
Summary.Salinity$Precipitation<-as.numeric(Summary.Salinity$Precipitation)

summary(Summary.Salinity)
```

## Nutrients

### All 
```{r}
TankNutrients<- ggplot(subset(Nutrients.tall, Treatment=="Ambient"),
                       aes (Time, Concentration, group=(Tank),
                                            colour=factor(Tank))) +
  #geom_vline(xintercept=1500)+
  geom_line(linetype=1)+
  geom_point(alpha=1, size=1, shape=21)+
  scale_y_continuous(#limits = c(0, 35),
                         breaks = seq(0, 35, 2),  
                       #  expand = c(0, 0),
                         name=("NH4 (uM)"))+
  scale_x_datetime(date_minor_breaks = "1 day", 
               name=("Date"))+
  geom_vline(xintercept = as.numeric(as_datetime("2020-10-04 23:00:00")), linetype=3)
  
TankNutrients+facet_wrap(Nutrient~., scales = "free")


TankNutrients<- ggplot(Nutrients.tall, aes (Time, Concentration, group=(Tank),
                                            colour=factor(Treatment))) +
  #geom_vline(xintercept=1500)+
  geom_line(linetype=1)+
  geom_point(alpha=1, size=1, shape=21)+
  scale_y_continuous(limits = c(0, 20),
                         breaks = seq(0, 35, 2),  
                       #  expand = c(0, 0),
                         name=("(uM)"))+
  scale_x_datetime(date_minor_breaks = "1 day", 
               name=("Date"))+
  geom_vline(xintercept = as.numeric(as_datetime("2020-10-04 23:00:00")), linetype=3)
  
TankNutrients+facet_wrap(Nutrient~., scales = "free")


```

```{r}
TankNutrients<- ggplot(subset(Nutrients.tall, Treatment=="Ambient"),
                       aes (Date, Concentration, colour=factor(Treatment))) +
  #geom_vline(xintercept=1500)+
  #geom_line(linetype=1)+
  geom_point(alpha=1, size=0.5, shape=21)+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") + 
  stat_summary(fun.y=mean, geom="point") +
  scale_y_continuous(#limits = c(0, 20),
                      breaks = seq(0, 35, 2),  
                      #  expand = c(0, 0),
                      name=("(uM)"))#+
  #scale_x_datetime(date_minor_breaks = "1 day", 
   #            name=("Date"))+
  #geom_vline(xintercept = as.numeric(as_datetime("2020-10-04 23:00:00")), linetype=3)
  
TankNutrients+facet_wrap(Nutrient~., scales = "free_y")


TankNutrients<- ggplot(Nutrients.tall, aes (Date, Concentration, colour=factor(Treatment))) +
  #geom_vline(xintercept=1500)+
  #geom_line(linetype=1)+
  #geom_point(alpha=1, size=1, shape=21)+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") + 
  stat_summary(fun.y=mean, geom="point") +
  scale_y_continuous(#limits = c(0, 20),
                      breaks = seq(0, 35, 2),  
                      #  expand = c(0, 0),
                      name=("(uM)"))+
  geom_vline(xintercept = as.numeric(as.Date("2020-10-04")), linetype=3)
TankNutrients+facet_wrap(~Nutrient, scales = "free_y")

TankNutrients<- ggplot(Nutrients,
                       aes (Date, NH4, shape=(sample), colour=factor(sample))) +
  #geom_vline(xintercept=1500)+
  #geom_line(linetype=1)+
  geom_line()+
  geom_point(alpha=1, size=1)+
  #stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  #stat_summary(fun.y=mean, geom="line") + 
  #stat_summary(fun.y=mean, geom="point") +
  scale_y_continuous(#limits = c(0, 20),
                      breaks = seq(0, 35, 1),  
                      #  expand = c(0, 0),
                      name=("NH4 (uM)"))+
  geom_vline(xintercept = as.numeric(as.Date("2020-10-04")), linetype=3)
TankNutrients+facet_wrap(~Tank, scales = "free_y")


NO3<- ggplot(Nutrients, aes (Date, N.N.uM., colour=factor(Treatment))) +
  #geom_vline(xintercept=1500)+
  #geom_line(linetype=1)+
  #geom_point(alpha=1, size=1, shape=21)+
  geom_boxplot()+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  #stat_summary(fun.y=mean, geom="line") + 
  #stat_summary(fun.y=mean, geom="point") +
  scale_y_continuous(#limits = c(0, 20),
                      breaks = seq(0, 35, 2),  
                      #  expand = c(0, 0),
                      name=("(uM)"))+
geom_vline(xintercept = as.numeric(as.Date("2020-10-04")), linetype=3)
NO3



```


```{r}
TankNutrients<- ggplot(Nutrients.tall, aes (Time, Concentration, colour=factor(Nutrient))) +
  #geom_vline(xintercept=1500)+
  #geom_line(linetype=1)+
  #geom_point(alpha=1, size=1, shape=21)+
  stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2 )+
  stat_summary(fun.y=mean, geom="line") + 
  stat_summary(fun.y=mean, geom="point") +
  scale_y_continuous(#limits = c(0, 20),
                      breaks = seq(0, 35, 2),  
                      #  expand = c(0, 0),
                      name=("(uM)"))+
  scale_x_datetime(date_minor_breaks = "1 day", 
               name=("Date"))+
  geom_vline(xintercept = as.numeric(as_datetime("2020-10-04 23:00:00")), linetype=3)
  
TankNutrients+facet_wrap(Treatment~Tank)
```

### NH4

```{r}

TankNH4<- ggplot(Nutrients., aes (x=Time)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=NH4, group=(Tank), colour=factor(Treatment)), linetype=2)+
  geom_point(aes(y=NH4, colour=factor(Treatment)), alpha=1, size=2, shape=21)+
  geom_hline(yintercept = 10, linetype=3)+
  geom_hline(yintercept = 20, linetype=3)+
  geom_hline(yintercept = 30, linetype=3)+
  
  scale_y_continuous(limits = c(0, 35),
                         breaks = seq(0, 35, 2),  
                         expand = c(0.01, 0),
                         name=("NH4 (uM)"))+
  scale_x_datetime(breaks = "1 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

TankNH4+facet_grid(sample~.)

```


```{r}

TankNutrients<- ggplot(Nutrients, aes (Time, NH4, colour=factor(Tank))) +
  #geom_vline(xintercept=1500)+
  #geom_line(linetype=2)+
  geom_point(alpha=1, size=2)+
  scale_y_continuous(limits = c(0, 35),
                         breaks = seq(0, 35, 2),  
                         expand = c(0, 0),
                         name=("NH4 (uM)"))+
  scale_x_datetime(date_minor_breaks = "1 day", 
               name=("Date"))

TankNutrients+facet_grid(Treatment~.)

```

### NH4
```{r}

TankNH4<- ggplot(Nutrients, aes (x=Time)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=NH4, group=(Tank), colour=factor(Treatment)), linetype=2)+
  geom_point(aes(y=NH4, colour=factor(Treatment)), alpha=1, size=2, shape=21)+
  geom_hline(yintercept = 10, linetype=3)+
  geom_hline(yintercept = 20, linetype=3)+
  geom_hline(yintercept = 30, linetype=3)+
  
  scale_y_continuous(limits = c(0, 35),
                         breaks = seq(0, 35, 2),  
                         expand = c(0.01, 0),
                         name=("NH4 (uM)"))+
  scale_x_datetime(breaks = "1 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

TankNH4+facet_grid(sample~.)


```

### NO3

```{r}

TankNO3<- ggplot(Nutrients, aes (x=Time)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=NO3.uM., group=(Tank), colour=factor(Treatment)), linetype=2)+
  geom_point(aes(y=NO3.uM., colour=factor(Treatment)), alpha=1, size=2, shape=21)+
  geom_hline(yintercept = 10, linetype=3)+
  geom_hline(yintercept = 20, linetype=3)+
  geom_hline(yintercept = 30, linetype=3)+
  
  scale_y_continuous(limits = c(0, 10),
                         breaks = seq(0, 10, 0.5),  
                         expand = c(0.01, 0),
                         name=("NO3 (uM)"))+
  scale_x_datetime(breaks = "1 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

TankNO3+facet_grid(sample~.)



TankNN<- ggplot(Nutrients, aes (x=Date)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=N.N.uM., group=(Tank), colour=factor(Tank)), linetype=2)+
  geom_point(aes(y=N.N.uM., colour=factor(Tank), shape=factor(Treatment)), alpha=1, size=2)+
  geom_hline(yintercept = 10, linetype=3)+
  geom_hline(yintercept = 20, linetype=3)+
  geom_hline(yintercept = 30, linetype=3)+
  
  scale_y_continuous(limits = c(0, 10),
                         breaks = seq(0, 10, 0.5),  
                         expand = c(0.01, 0),
                         name=("NO3 + NO2 (uM)"))+
  scale_x_date(breaks = "1 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    limits = as.Date(c("2020-09-20","2020-10-20")),
                    name=("Date"))

TankNN+facet_grid(sample~Treatment)

TankNh4<- ggplot(Nutrients, aes (x=Time)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=NH4, group=(Tank), colour=factor(Tank)), linetype=2)+
  geom_point(aes(y=NH4, colour=factor(Tank), shape=factor(Treatment)), alpha=1, size=2)+
  geom_hline(yintercept = 10, linetype=3)+
  geom_hline(yintercept = 20, linetype=3)+
  geom_hline(yintercept = 30, linetype=3)+
  geom_vline(xintercept = as.Date("2020-10-05"), linetype=3)+

  
  scale_y_continuous(limits = c(0, 15),
                         breaks = seq(0, 35, 2),  
                         expand = c(0.01, 0),
                         name=("NH4 (uM)"))+
  scale_x_datetime(breaks = "1 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

TankNh4+facet_grid(sample~.)

TankPO3<- ggplot(Nutrients, aes (x=Time)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=PO4..uM., group=(Tank), colour=factor(Treatment)), linetype=2)+
  geom_point(aes(y=PO4..uM., colour=factor(Treatment)), alpha=1, size=2, shape=21)+
  geom_hline(yintercept = 10, linetype=3)+
  geom_hline(yintercept = 20, linetype=3)+
  geom_hline(yintercept = 30, linetype=3)+
  
  scale_y_continuous(limits = c(0, 10),
                         breaks = seq(0, 10, 0.5),  
                         expand = c(0.01, 0),
                         name=("PO3 (uM)"))+
  scale_x_datetime(breaks = "1 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

TankPO3+facet_grid(sample~.)

```


```{r}
 TankNutrients<- ggplot(Nutrients, aes (Time, NH4, colour=factor(Tank))) +
  #geom_vline(xintercept=1500)+
  geom_line(linetype=2)+
  geom_point(alpha=1, size=2)+
  scale_y_continuous(limits = c(0, 35),
                         breaks = seq(0, 35, 2),  
                         expand = c(0, 0),
                         name=("NH4 (uM)"))+
  scale_x_datetime(date_minor_breaks = "1 day", 
               name=("Date"))

TankNutrients+facet_grid(Treatment~.)

```

## Salinity

```{r}
Salinity_plot<- ggplot(Salinity, aes (x=Time, y=Salinity)) +
  #geom_vline(xintercept=1500)+
  geom_line()+
    scale_y_continuous(limits = c(15, 36),
                         breaks = seq(15, 35, 2),  
                         expand = c(0.01, 0),
                         name=("Salinity (?)"))+
  scale_x_datetime(breaks = "1 week", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

Salinity_plot


Salinity_summary<- ggplot(Summary.Salinity, aes (x=Date)) +
  #geom_vline(xintercept=1500)+
  geom_line(aes(y=min), colour="blue")+
  geom_line(aes(y=max), colour="red")+
  geom_line(aes(y=mean), colour="black")+
  geom_line(aes(y=Precipitation*10), colour="black")+
  geom_hline(yintercept = 30, linetype=3)+
  geom_hline(yintercept = 33, linetype=3)+
  
  # Data collection
  geom_vline(xintercept = as.Date("2020-08-12"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-04"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-11"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-14"), linetype=4)+
  geom_vline(xintercept = as.Date("2020-09-18"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-25"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-10-02"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-10-09"), linetype=3)+
  
  geom_hline(yintercept = 33, linetype=3)+
  
  scale_y_continuous(limits = c(0, 36),
                         breaks = seq(0, 35, 2),  
                         expand = c(0.01, 0),
                         name=("Salinity (?)"))+
  scale_x_date(breaks = "3 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))

Salinity_summary

```

```{r}
All_summary<- ggplot() +
  
  geom_hline(yintercept = 30, linetype=3)+
  geom_hline(yintercept = 33, linetype=3)+
  
  # Data collection
  geom_vline(xintercept = as.Date("2020-08-12"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-08-21"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-04"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-11"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-14"), linetype=4)+
  geom_vline(xintercept = as.Date("2020-09-18"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-09-25"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-10-02"), linetype=3)+
  geom_vline(xintercept = as.Date("2020-10-09"), linetype=3)+
  
  geom_line(data=Summary.Salinity, aes(x=Date, y=min), colour="blue")+
  geom_line(data=Summary.Salinity, aes(x=Date, y=max), colour="red")+
  geom_line(data=Summary.Salinity, aes( x=Date, y=mean), colour="black")+
  
  geom_line(data=Summary.Salinity, aes(x=Date, y=Precipitation+20), colour="black")+
  geom_point(data=Summary.Salinity, aes(x=Date, y=Precipitation+20), colour="black", alpha=1, size=1)+
  
  #geom_line(data=Nutrients, aes (x=as.Date(Time), y=NH4, group=factor(Tank), 
  #                               colour=Treatment), linetype=2) +
  #geom_point(data=Nutrients, aes (x=as.Date(Time), y=NH4, group=factor(Tank),
   #                               colour=Treatment), alpha=1, size=2, shape=21) +
  geom_line(data=Nutrients, aes (x=Date, y=PO4..uM., group=factor(Tank), 
                                 colour=Treatment), linetype=1) +
  
  
  scale_y_continuous(limits = c(0, 36),
                         breaks = seq(0, 35, 2),  
                         expand = c(0.01, 0),
                         name=("Salinity / NH4 (uM) / Precipitation +20in"))+
  scale_x_date(breaks = "3 day", 
                   #limits = c(Sys.Date() - 20, NA),
                    #limits = as.Date(c("2020-09-14","2020-10-03")),
                    name=("Date"))
All_summary

```


```{r}
# Temperature

Samples <- data.frame(table(Nutrients$Sample.ID))
  colnames(Samples)<-c("Sample.ID","RanA")
  Nutrients_sample<-plyr::join(Nutrients, Samples, type = "left")
  
  Nutrients_sample<-Nutrients[duplicated(Nutrients$Sample.ID), ]
  
  Nutrients_sample <- Nutrients_sample[(Nutrients_sample$RanA>1),]
  
  summary(Nutrients_sample)
  
  # Tall format
  Samples.tall <- gather(Nutrients_sample, Nutrient, Concentration, 
                      NH4:PO4.uM., factor_key=TRUE)
  
  samples2 <- spread(Samples.tall,sample, Concentration)

  summary(samples2)
  
  
  
 Sample_type<- ggplot(samples2, aes (Frozen, Chl))+
   geom_smooth(method = lm)+
  geom_point(aes(colour=Date),alpha=1, size=2, shape=21)+
  geom_abline(intercept = 0, slope = 1, linetype=2)+
   
  scale_y_continuous(#limits = c(0, 35),
                        breaks = seq(0,20, 2),  
  #                       expand = c(0, 0),
                        name=("Concentration (uM) - Chloroform"))+
  scale_x_continuous(#limits = c(0, 35),
                        breaks = seq(0,20, 2),  
  #                       expand = c(0, 0),
                        name=("Concentration (uM) - Frozen"))
  
Sample_type+facet_wrap(~Nutrient, scales = "free")
  
```

