---
title: "Acer mortality_Nutrients+Disease"

author: "Ana Palacio"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    df_print: paged
    theme: united
bibliography: packages.bib
nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
```

# General project set-up 

```{r libraries, results="hide", echo=FALSE}

# Load all libraries and sources required to run the script
  library(ggplot2)    
  library(tidyverse)
  library(ggthemes)
  library(survival)
  library(survminer)
  #library(rms)
   
# Default ggplot settings
    #Fill.colour <- c("blue", "red4", "green4", "black" )
    Fill.colour <- c("deepskyblue", "indianred1", "blue4", "red4")

    ggthe_bw<- theme_bw() +
      theme(plot.background=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )
```

# Importa and organize data

```{r, echo=FALSE}
# Data
    Survival.data<-read.csv("Data/Acer_Mortality2.csv", header = TRUE)
    summary(Survival.data)
    Survival.data$Date<-as.Date(Survival.data$Date)
    Survival.data$Day<-as.numeric(Survival.data$Date)-18518
    Survival.data$Fu.time_texp<-Survival.data$Day
    Survival.data$Treatment<-paste(Survival.data$Nutrients, 
                                   Survival.data$Disease, sep = "+" )
    Survival.data$Gen_Treat<-paste(Survival.data$Genotype,
                                   Survival.data$Treatment, sep = "-" )
    Survival.data$Genotype<-as.factor(Survival.data$Genotype)
```

```{r}
# Filter data 
    Survival.data_1<-Survival.data
    Survival.data_1<-filter(Survival.data_1, Treatment!="Ambient+Heat")
    Survival.data_1<-filter(Survival.data_1, Genotype!="U41")
    #Survival.data_1$Treatment <- droplevels(Survival.data_1$Treatment)
    Survival.data_1$Genotype <- droplevels(Survival.data_1$Genotype)
    
    Survival.data_1$Treatment<-factor(Survival.data_1$Treatment,
                                      levels = c("Ambient+Placebo", "Ambient+Disease",
                                                  "NH4+Placebo", "NH4+Disease"))
    Survival.data_1$Genotype<-factor(Survival.data_1$Genotype, 
                               levels=c("FM19", "FM6", "FM9", "U44", "FM14", "Elkhorn",
                                        "K2", "Acerv2", "Kelsey-1", "Cooper-9"))
    #summary(Survival.data_1$Genotype)
    #summary(Survival.data_1$Treatment)
    
    
# Create survival object (Fit survival data using the Kaplan-Meier method)
    surv_object_1 <- Surv(time = Survival.data_1$Fu.time_texp, 
                          event = Survival.data_1$Fu.stat_exp)
    #surv_object_1 

```

## Model 0 (Genotype)

```{r}
# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0 <- survfit(surv_object_1 ~ Genotype, conf.type = "log-log", 
                    data = Survival.data_1)
    summary(fit0)
  # Plot the survival model
    Genotype_only<-ggsurvplot(fit0, data = Survival.data_1, pval = TRUE,
               risk.table=F, tables.height=0.4, conf.int = F, n.risk   = TRUE )
    Genotype_only

```

## Model 1 (Treatment)

```{r}
    fit1 <- survfit(surv_object_1 ~ Treatment, conf.type = "log-log", 
                    data = Survival.data_1)
    summary(fit1)
  # Plot the survival model
    Treatment_only<-ggsurvplot(fit1, data = Survival.data_1, pval = TRUE,
              risk.table=F, 
              palette=Fill.colour, tables.height=0.4,
              conf.int = T, n.risk   = TRUE)
    Treatment_only
    ggsave(file="Treatment.svg", print(ggsurvplot(fit1, data = Survival.data_1, pval = TRUE,
              risk.table=F, 
              palette=Fill.colour, tables.height=0.4,
              conf.int = T, n.risk   = TRUE)), width=5, height=5, dpi = 300)
```

## Model 2 (Genotype + Treatment)

```{r}
# Kaplan-Meier estimator. The "log-log" confidence interval is- preferred.
    
    fit2 <- survfit(surv_object_1 ~ Genotype + Treatment, data = Survival.data_1)
    
    summary(fit2)
    #summary(fit2)$table
    #sd1<-survdiff(surv_object_1~Treatment, data = Survival.data_1)
    #1 - pchisq(sd1$chisq, length(sd1$n) - 1)# pvalue
    results<-summary(fit2)
    #results<-summary(fit2, times = c(52))
    save.df <- as.data.frame(results[c("strata", "time", "n.risk", "n.event", "surv", "std.err")])
    write.csv(save.df, file = "Outputs/survival.csv")
    
```

### Plot by treatments 

```{r, echo=FALSE}
# Plot the survival model
    GenTre_1<-ggsurvplot(fit2, data = Survival.data_1, pval = TRUE,
           risk.table=F,  tables.height=0.5)
    #GenTre_1
    
    GenotypeP<-ggsurvplot_facet(fit2, data = Survival.data_1,
                                facet.by="Genotype", 
                  risk.table=F, # tables.height=0.5, 
                   palette=Fill.colour, 
                 nrow = 6, alpha=1, linetype=1) +
        geom_vline(xintercept = 48, linetype="dashed", 
                color = "gray")
    GenotypeP
    #ggsave("Outputs/Genotype_T.svg", print(GenotypeP), width=5.5, height=8, dpi = 300)
```

### Plot by genotype

```{r, echo=FALSE}
  TreatmentP<-ggsurvplot_facet(fit2, data = Survival.data_1, 
                 facet.by="Treatment", 
                 # risk.table=T, tables.height=0.5, 
                 nrow = 3, alpha=1,
                 linetype=1) +
      #geom_vline(xintercept = 48, linetype="dashed", 
      #          color = "gray") +
      #geom_vline(xintercept = 49, linetype="dashed", 
      #          color = "gray") +
      annotate("rect",xmin=(48), ymin=0, xmax = 49, ymax = 1, 
               alpha=0.5)+
      # Tissue samples
      annotate("point",x=c(47), y=c(0), 
           shape=4, size=2)+
      annotate("point",x=c(58), y=c(0), 
           shape=4, size=2)
    TreatmentP
  #ggsave("Outputs/Genotype_S.svg", print(TreatmentP), width=5.5, height=6,dpi = 300)
```

## Model 3 (Genotype * Treatment)

```{r}
# Treatment and genotype model 2
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit3 <- survfit(surv_object_1 ~ Gen_Treat, data = Survival.data_1)
    summary(fit3)
    # Plot the survival model
    ggsurvplot(fit3, data = Survival.data_1, pval = TRUE, conf.int = F,
           risk.table=F,  tables.height=0.5)
```


Do not run
```{r}
# fit.coxph0 <- coxph(surv_object ~ Genotype, data = Survival.data)
# ggforest(fit.coxph0, data = Survival.data)
# fit.coxph0

# fit.coxph1 <- coxph(surv_object ~ Treatment, data = Survival.data)
# ggforest(fit.coxph1, data = Survival.data)
# fit.coxph1
# 
# fit.coxph2 <- coxph(surv_object ~ factor(Treatment) + factor (Genotype), data = Survival.data)
# ggforest(fit.coxph, data = Survival.data)
# fit.coxph2
# summary(fit.coxph2)
# 
# fit.coxph3 <- coxph(surv_object ~ factor(Gen_Treat), data = Survival.data)
# ggforest(fit.coxph3, data = Survival.data)
# fit.coxph3
# summary(fit.coxph3)

```

# 2. For hazard ratios: Remove the ambient-placebo data and run models again

## 2.1 Ambient+Disease

```{r}
# Data
    Survival.data2<-Survival.data_1[(Survival.data_1$Treatment=="Ambient+Disease"),]
    Survival.data2$Treatment <- droplevels(Survival.data2$Treatment)
    #summary(Survival.data2)
    #summary(Survival.data2$Genotype)
    #summary(Survival.data2$Treatment)
    
  ## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object2 <- Surv(time = Survival.data2$Fu.time_texp,
                       event = Survival.data2$Fu.stat_exp)
  #surv_object2 
    ```


```{r}
# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0_2 <- survfit(surv_object2 ~ Genotype, 
                      #conf.type = "log-log",
                      data = Survival.data2)
    summary(fit0_2)
    surv_pvalue(fit0_2)
    coxfit0_2 <- coxph(surv_object2 ~ Genotype, data = Survival.data2)
  # Plot the survival model
    Genotype_only2<-ggsurvplot(fit0_2, data = Survival.data2, pval = TRUE,
               risk.table=F, tables.height=0.4, conf.int = T, n.risk = TRUE,
               #risk.table.y.text = FALSE, 
               break.time.by=15, xlim=c(0,58), 
           risk.table.title="Number of A. cervicornis at risk")
    Genotype_only2
    
    #ggsave("Outputs/Fig_2_Surv_Genotype.svg", 
    #       Genotype_only2$plot, width=4.5, height=3.5,dpi = 300)
    #ggsave("Outputs/Fig_2_Surv_Genotype.pdf", print(Genotype_only2),
    #       width=4.5, height=4.5,dpi = 300)

fit.coxph0_2 <- coxph(surv_object2 ~ Genotype, data = Survival.data2)
HazardRatio<-ggforest(fit.coxph0_2, data = Survival.data2)
fit.coxph0_2

```

## 2.2 NH4-Placebo

```{r}
# Data
    Survival.data3<-Survival.data_1[(Survival.data_1$Treatment=="NH4+Placebo"),]
    Survival.data3$Treatment <- droplevels(Survival.data3$Treatment)
    #summary(Survival.data3)
    #summary(Survival.data3$Genotype)
    #summary(Survival.data3$Treatment)
    
    
  ## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object3 <- Surv(time = Survival.data3$Fu.time_texp, 
                       event = Survival.data3$Fu.stat_exp)
  #surv_object3 
    ```


```{r}
# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0_3 <- survfit(surv_object3 ~ Genotype, 
                      conf.type = "log-log",
                      data = Survival.data3)
    summary(fit0_3)
    surv_pvalue(fit0_3)
    coxfit0_3 <- coxph(surv_object3 ~ Genotype, data = Survival.data3)
  # Plot the survival model
    Genotype_only3<-ggsurvplot(fit0_3, data = Survival.data3, pval = TRUE,
               risk.table=F, tables.height=0.4, conf.int = T, n.risk = TRUE,
               #risk.table.y.text = FALSE, 
               break.time.by=15, xlim=c(0,58), 
           risk.table.title="Number of A. cervicornis at risk")
    Genotype_only3
    
    #ggsave("Outputs/Fig_3_Surv_Genotype.svg", 
    #       Genotype_only3$plot, width=4.5, height=3.5,dpi = 300)
    #ggsave("Outputs/Fig_3_Surv_Genotype.pdf", print(Genotype_only3),
    #       width=4.5, height=4.5,dpi = 300)

fit.coxph0_3 <- coxph(surv_object3 ~ Genotype, data = Survival.data3)
HazardRatio3<-ggforest(fit.coxph0_3, data = Survival.data3)
HazardRatio3
fit.coxph0_3

```

## 2.3 NH4-Pathoghen

```{r}
# Data
    Survival.data4<-Survival.data_1[(Survival.data_1$Treatment=="NH4+Disease"),]
    Survival.data4$Treatment <- droplevels(Survival.data4$Treatment)
    #summary(Survival.data4)
    #summary(Survival.data4$Genotype)
    #summary(Survival.data4$Treatment)
    
    
  ## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object4 <- Surv(time = Survival.data4$Fu.time_texp,
                       event = Survival.data4$Fu.stat_exp)
  #surv_object4 
    ```


```{r}
# Only genotype model
  # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit0_4 <- survfit(surv_object4 ~ Genotype, 
                      conf.type = "log-log",
                      data = Survival.data4)
    summary(fit0_4)
    surv_pvalue(fit0_4)
    coxfit0_4 <- coxph(surv_object4 ~ Genotype, data = Survival.data4)
  # Plot the survival model
    Genotype_only4<-ggsurvplot(fit0_4, data = Survival.data4, pval = TRUE,
               risk.table=F, tables.height=0.4, conf.int = T, n.risk = TRUE,
               #risk.table.y.text = FALSE, 
               break.time.by=15, xlim=c(0,58), 
           risk.table.title="Number of A. cervicornis at risk")
    Genotype_only4
    
    #ggsave("Outputs/Fig_4_Surv_Genotype.svg", 
    #       Genotype_only4$plot, width=4.5, height=4.5,dpi = 400)
    #ggsave("Outputs/Fig_4_Surv_Genotype.pdf", print(Genotype_only4),
    #       width=4.5, height=4.5,dpi = 400)

fit.coxph0_4 <- coxph(surv_object4 ~ Genotype, data = Survival.data4)
HazardRatio4<-ggforest(fit.coxph0_4, data = Survival.data4)
HazardRatio4
fit.coxph0_4

```


# 3 Treatment + Genotype

```{r}

# Data
    Survival.data5<-Survival.data_1[(Survival.data_1$Treatment!="Ambient+Placebo"),]
    Survival.data5$Treatment <- droplevels(Survival.data5$Treatment)
    Survival.data5$Treatment<-factor(Survival.data5$Treatment, 
                                     levels = c("NH4+Placebo", "Ambient+Disease", "NH4+Disease"))
    #summary(Survival.data5)
    #summary(Survival.data5$Genotype)
    #summary(Survival.data5$Treatment)
    
    
  ## Add survival object (Fit survival data using the Kaplan-Meier method)
  surv_object5 <- Surv(time = Survival.data5$Fu.time_texp, 
                       event = Survival.data5$Fu.stat_exp)
  #surv_object5 
  
# Treatment and genotype model 1 
    # Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
    fit5 <- survfit(surv_object5 ~ Genotype + Treatment, data = Survival.data5)
    summary(fit5)
    # Plot the survival model
    GenTre_1_2<-ggsurvplot(fit5, data = Survival.data5, pval = TRUE, conf.int = T,
           risk.table=F,  tables.height=0.5)
    #GenTre_1_2
    
    ggsurvplot_facet(fit5, data = Survival.data5, 
                 facet.by="Genotype", risk.table=T, conf.int = T,
                 tables.height=0.5, nrow = 6, alpha=1,
                 palette=Fill.colour, linetype=1)


    Ac_facet_G<-ggsurvplot_facet(fit5, data = Survival.data5, 
                 facet.by="Treatment", risk.table=F, conf.int = F,
                 tables.height=0.5, nrow = 3, alpha=0.5,
                 linetype=1)
    Ac_facet_G
    
    #ggsave("Outputs/Ac_facet.svg", Ac_facet_G, width=4, height=6,dpi = 300)
    
```

```{r}

#ggsave("Outputs/Fig_S1_HazardRatio.svg", HazardRatio, width=6, height=4,dpi = 300)
    
fit.coxph1_2 <- coxph(surv_object5 ~ Treatment, data = Survival.data5)
ggforest(fit.coxph1_2, data = Survival.data5)
fit.coxph1_2

fit.coxph2_2 <- coxph(surv_object5 ~ Treatment + Genotype, data = Survival.data5)
ggforest(fit.coxph2_2, data = Survival.data5)
fit.coxph2_2
summary(fit.coxph2_2)
```

# Packages used

```{r}
# Creates bibliography 
#knitr::write_bib(c(.packages()), "packages.bib")
```